{
 "title": "Memory Min Mean and Max across Components",
 "time": { "from": "2020-11-03T16:18:48.001Z", "to": "2020-11-03T16:18:57.001Z" },
 "templating": {
  "list": [
   { "name": "container", "query": "ldms-data.save" },
   {
    "name": "schema",
    "query": "query=schema&container=$container"
   },
   {
    "name": "job_id",
    "query": "query=jobs&container=$container&schema=meminfo"
   }
  ]
 },
 "panels": [
  {
   "title": "Active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "analysis": "compMinMeanMax",
     "container": "$container",
     "index": "job_comp_time",
     "job_id": "$job_id",
     "query_type": "analysis",
     "schema": "$schema",
     "target": "Active",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MemFree",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "analysis": "compMinMeanMax",
     "container": "$container",
     "index": "job_comp_time",
     "job_id": "$job_id",
     "query_type": "analysis",
     "schema": "$schema",
     "target": "MemFree",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Writeback",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "analysis": "compMinMeanMax",
     "comp_id": "0",
     "container": "$container",
     "index": "job_comp_time",
     "job_id": "$job_id",
     "query_type": "analysis",
     "schema": "$schema",
     "target": "Writeback",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "AnonPages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "analysis": "compMinMeanMax",
     "comp_id": "0",
     "container": "$container",
     "index": "job_comp_time",
     "job_id": "$job_id",
     "query_type": "analysis",
     "schema": "$schema",
     "target": "AnonPages",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Dirty Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "analysis": "compMinMeanMax",
     "comp_id": "0",
     "container": "$container",
     "index": "job_comp_time",
     "job_id": "$job_id",
     "query_type": "analysis",
     "schema": "$schema",
     "target": "Dirty",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Mapped Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "analysis": "compMinMeanMax",
     "comp_id": "0",
     "container": "$container",
     "index": "job_comp_time",
     "job_id": "$job_id",
     "query_type": "analysis",
     "schema": "$schema",
     "target": "Mapped",
     "type": "timeserie"
    }
   ]
  }
 ]
}