{
 "title": "Papi Job Cache Dashboard",
 "time": { "from": "2020-10-21T19:47:48.000Z", "to": "2020-10-21T19:49:27.000Z" },
 "templating": {
  "list": [
   { "name": "container", "query": "ldms-data" },
   { "name": "job_id", "query": "52980" }
  ]
 },
 "panels": [
  {
   "title": "L1 Instruction Cache Misses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "PAPI_L1_ICM",
     "target": "PAPI_L1_ICM",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "L1 Data Cache Misses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "PAPI_L1_DCM",
     "target": "PAPI_L1_DCM",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "L1 Miss Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "target": "l1_miss_rate",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "L1 Miss Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "PAPI_L1_ICM",
     "target": "l1_miss_ratio",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "L2 Instruciton Cache Accesses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "PAPI_L2_ICA",
     "target": "PAPI_L2_ICA",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "L2 Total Cache Accesses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "PAPI_L2_TCA",
     "target": "PAPI_L2_TCA",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "L2 Total Cache Misses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "PAPI_L2_TCM",
     "target": "PAPI_L2_TCM",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "L2 Miss Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "target": "l2_miss_rate",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "L2 Miss Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "PAPI_L2_ICM",
     "target": "l2_miss_ratio",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "L2 Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "PAPI_L2_TCA",
     "target": "l2_bw",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "L3 Total Cache Accesses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "PAPI_L3_TCA",
     "target": "PAPI_L3_TCA",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "L3 Total Cache Misses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "PAPI_L3_TCM",
     "target": "PAPI_L3_TCM",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "L3 Miss Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "PAPI_L3_TCM",
     "target": "l3_miss_rate",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "L3 Miss Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "PAPI_L3_TCA",
     "target": "l3_miss_ratio",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "L3 Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "PAPI_L3_TCA",
     "target": "l3_bw",
     "type": "timeserie"
    }
   ]
  }
 ]
}