{
 "title": "Papi Job CPU Statistics",
 "time": { "from": "2020-10-21T19:12:51.000Z", "to": "2020-10-21T19:14:29.000Z" },
 "templating": {
  "list": [
   { "name": "container", "query": "papi" },
   { "name": "job_id", "query": "46689" }
  ]
 },
 "panels": [
  {
   "title": "Load Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "$schema",
     "target": "load_rate",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Store Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "$schema",
     "target": "store_rate",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Load Instructions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "$schema",
     "target": "ld_ins",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Store Instructions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "$schema",
     "target": "sr_ins",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Clock Cycles per Instruction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "$schema",
     "target": "cpi",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Ratio of Load/Store to all Instruction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "$schema",
     "target": "uopi",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Floating Point Instructions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "$schema",
     "target": "fp_ops",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Branch Instructions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "container": "$container",
     "index": "comp_time",
     "job_id": "$job_id",
     "query_type": "papi_timeseries",
     "schema": "$schema",
     "target": "br_ins",
     "type": "timeserie"
    }
   ]
  }
 ]
}